# Generated by Django 4.2.18 on 2025-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=30)),
                ('second_password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('flag_zakaz', models.BooleanField(default='False')),
                ('flag_sdelano', models.BooleanField(default='False')),
            ],
        ),
    ]
